#!/bin/sh

PASH_BIN=${PASH_BIN:=pash}
PASSWORD_STORE=${PASH_DIR:=${XDG_DATA_HOME:=$HOME/.local/share}/pash}

git_commit() {
    git -C "$PASSWORD_STORE" add "$1".gpg && git -C "$PASSWORD_STORE" commit -m "$2"
}

die() {
    printf 'error: %s.\n' "$1" >&2
    exit 1
}

main() {
    command -v $PASH_BIN >/dev/null 2>&1 || die "pash is not found" 
    command -v git >/dev/null 2>&1 || die "Git is not installed"
    [ -d "$PASSWORD_STORE" ] && [ -d "$PASSWORD_STORE/.git" ] || die "Git repository under $PASSWORD_STORE doesn't exist"

    case $1 in
        a*)
            command $PASH_BIN "$@" && {
                for arg in "$@"
                do
                    shift
                    case $arg in
                        -*)
                            continue
                            ;;
                    esac
                    set -- "$@" "$arg"
                done
            } && git_commit "$2" "Added $2 to the store"
        ;;
    d*)
        command $PASH_BIN "$@" && git_commit "$2" "Removed $2 from the store"
        ;;
    g*)
        shift
        git -C "$PASSWORD_STORE" "$@"
        ;;
    *)  command $PASH_BIN "$@" ;;
esac
}

set +x -f

main "$@"
